default:
  db_host: "35.243.133.29"
  db_port: 5432
  db_name: "sragent"
  db_user: "postgres"
  db_password: "GCP_SQL_DB_PASSWORD_PROD"
  db_timeout: 30

test:
  db_name: "sragent-test"
  db_password: "GCP_SQL_DB_PASSWORD_TEST"

