default:
  db_host: "35.243.133.29"
  db_port: 5432
  db_user: "postgres"
  db_timeout: 30

test:
  db_name: "sragent-test"
  models:
    default: "o4-mini"
    esearch: "o4-mini"
    esummary: "o4-mini"
    elink: "o4-mini"
    efetch: "o4-mini"
    sequences: "o4-mini"
    ncbi_fetch: "o4-mini"
    bigquery: "o4-mini"
    entrez: "o4-mini"
    sragent: "o4-mini"
    tissue_ontology: "o4-mini"
    convert_router: "o4-mini"
    metadata_router: "o4-mini"
    metadata: "gpt-4.1"
    accessions: "o4-mini"
    entrez_convert: "o4-mini"
    find_datasets: "o4-mini"
  temperature:
    default: 0.1
    esearch: 0.1
    esummary: 0.1
    elink: 0.1
    efetch: 0.1
    sequences: 0.1
    ncbi_fetch: 0.1
    bigquery: 0.1
    entrez: 0.1
    sragent: 0.1
    tissue_ontology: 0.1
    metadata: 0.1
    convert_router: 0.1
    metadata_router: 0.1
    accessions: 0.1
    entrez_convert: 0.1
    find_datasets: 0.1
  reasoning_effort:
    default: "low"
    esearch: "low"
    esummary: "low"
    elink: "low"
    efetch: "low"
    sequences: "low"
    ncbi_fetch: "low"
    bigquery: "medium"
    entrez: "medium"
    sragent: "medium"
    tissue_ontology: "medium"
    metadata: "high"
    convert_router: "low"
    metadata_router: "medium"
    accessions: "low"
    entrez_convert: "medium"
    find_datasets: "medium"
    
prod:
  db_name: "sragent-prod"
  models:
    default: "o4-mini"
    esearch: "o4-mini"
    esummary: "o4-mini"
    elink: "o4-mini"
    efetch: "o4-mini"
    sequences: "o4-mini"
    ncbi_fetch: "o4-mini"
    bigquery: "o4-mini"
    entrez: "o4-mini"
    sragent: "o4-mini"
    tissue_ontology: "o4-mini"
    convert_router: "o4-mini"
    metadata_router: "o4-mini"
    metadata: "gpt-4.1"
    accessions: "o4-mini"
    entrez_convert: "o4-mini"
    find_datasets: "o4-mini"
  temperature:
    default: 0.1
    esearch: 0.1
    esummary: 0.1
    elink: 0.1
    efetch: 0.1
    sequences: 0.1
    ncbi_fetch: 0.1
    bigquery: 0.1
    entrez: 0.1
    sragent: 0.1
    tissue_ontology: 0.1
    metadata: 0.1
    convert_router: 0.1
    metadata_router: 0.1
    accessions: 0.1
    entrez_convert: 0.1
    find_datasets: 0.1
  reasoning_effort:
    default: "low"
    esearch: "low"
    esummary: "low"
    elink: "low"
    efetch: "low"
    sequences: "low"
    ncbi_fetch: "low"
    bigquery: "medium"
    entrez: "medium"
    sragent: "medium"
    tissue_ontology: "medium"
    metadata: "high"
    convert_router: "low"
    metadata_router: "medium"
    accessions: "low"
    entrez_convert: "medium"
    find_datasets: "medium"

claude:
  db_name: "sragent-test"
  models:
    default: "claude-3-7-sonnet-latest"
  temperature:
    default: 0.1
  reasoning_effort:
    default: "low"
    esearch: "low"
    esummary: "low"
    elink: "low"
    efetch: "low"
    sequences: "low"
    ncbi_fetch: "low"
    bigquery: "medium"
    entrez: "medium"
    sragent: "medium"
    tissue_ontology: "medium"
    metadata: "high"
    convert_router: "low"
    metadata_router: "medium"
    accessions: "low"
    entrez_convert: "medium"
    find_datasets: "medium"